import type { ParsedJobHeader, ParsedStepHeader } from "./types";

const GUID_PATTERN = /\b[A-Z][A-Z0-9]{4,}\.[A-Z0-9]{4,}\b/g;
const JOB_KEYS = [
  "Job",
  "Description",
  "Metadata Server",
  "Port",
  "Location",
  "Server",
  "Source Tables",
  "Target Tables",
  "Generated on",
  "Generated by",
  "Version"
] as const;
const STEP_KEYS = [
  "Step",
  "Transform",
  "Description",
  "Source Table",
  "Source Tables",
  "Target Table",
  "Target Tables",
  "Quick Note",
  "Warnings"
] as const;

export function parseJobHeader(lines: readonly string[]): ParsedJobHeader {
  const sections = parseSections(lines, JOB_KEYS);
  return {
    job: sectionToInline(sections.get("Job")),
    description: sectionToInline(sections.get("Description"))
  };
}

export function parseStepHeader(lines: readonly string[]): ParsedStepHeader {
  const sections = parseSections(lines, STEP_KEYS);
  return {
    step: sectionToInline(sections.get("Step")),
    transform: sectionToInline(sections.get("Transform")),
    description: sectionToInline(sections.get("Description")),
    quickNote: sectionToLines(sections.get("Quick Note")),
    warnings: sectionToLines(sections.get("Warnings"))
  };
}

function parseSections(lines: readonly string[], keys: readonly string[]): Map<string, string[]> {
  const sections = new Map<string, string[]>();
  let currentKey: string | null = null;
  for (const raw of lines) {
    const unwrapped = unwrapBannerLine(raw);
    if (!unwrapped || isBorderLine(unwrapped)) continue;
    const colonIdx = unwrapped.indexOf(":");
    const candidateKey = colonIdx >= 0 ? unwrapped.slice(0, colonIdx).trim() : "";
    const matchedKey = keys.find((key) => key === candidateKey);
    if (matchedKey) {
      currentKey = matchedKey;
      const value = unwrapped.slice(colonIdx + 1).trim();
      const list = sections.get(matchedKey) ?? [];
      if (value) list.push(value);
      sections.set(matchedKey, list);
    } else if (currentKey) {
      sections.get(currentKey)?.push(unwrapped);
    }
  }
  return sections;
}

function unwrapBannerLine(line: string): string {
  let s = line.trim();
  if (s.startsWith("/*")) s = s.slice(2);
  if (s.endsWith("*/")) s = s.slice(0, -2);
  s = s.trim();
  if (s.startsWith("*")) s = s.slice(1);
  if (s.endsWith("*")) s = s.slice(0, -1);
  return s.trim();
}

function isBorderLine(line: string): boolean {
  return /^[=*]+$/.test(line);
}

function stripGuids(value: string): string {
  return value.replace(GUID_PATTERN, "").replace(/\s+/g, " ").trim();
}

function sectionToInline(values: string[] | undefined): string | undefined {
  if (!values || values.length === 0) return undefined;
  const text = stripGuids(values.join(" "));
  return text.length > 0 ? text : undefined;
}

function sectionToLines(values: string[] | undefined): string[] | undefined {
  if (!values || values.length === 0) return undefined;
  const cleaned = values.map((v) => stripGuids(v)).filter((v) => v.length > 0);
  return cleaned.length > 0 ? cleaned : undefined;
}
