import { findMacroEnd } from "./macroBalancer";
import type { Segment } from "./types";

// Allowlist philosophy — read before adding entries.
//
// SAS Data Integration Studio (DIS) generates jobs from a fixed code template.
// That template emits specific macro definitions, %let assignments, and
// pseudo-comments around the user's actual logic. We strip ONLY the items
// generated by that template; anything authored by a developer is kept.
//
// BOILERPLATE_MACROS — DIS framework-generated macros. Adding a name here
// unconditionally drops every `%macro <name> ... %mend;` block from the input.
// Do NOT add user-authored macros (e.g. `%macro etls_loader` — real example
// from the Bell file, contains the actual proc append loader logic). The
// `etls_*` prefix alone does NOT mean boilerplate.
//
// BOILERPLATE_LET_NAMES — DIS framework-managed runtime metadata variables.
// Adding a name here unconditionally drops every `%let <name> = ...;` line.
// Do NOT add user-authored variables sharing the `etls_*` prefix (e.g.
// `etls_tableExist`, `etls_lastTable`, `etls_tableOptions`, `etls_numIndex`
// are all user-authored loader state, not framework metadata).
//
// STRIPPABLE_NOISE_PATTERNS — anchored regex for the canonical DIS-generated
// pseudo-comments and `%put` statements. Anchored with `^...$` against the
// trimmed line so a developer comment that starts with a recognized phrase
// but adds extra context (e.g. their own annotation after the canonical
// "Runtime statistics macros" text) is NOT stripped. Never use prefix
// matching here; that was the v1 silent-data-loss footgun Phase 1 fixed.

const BOILERPLATE_MACROS = new Set([
  "etls_startPerformanceStats",
  "etls_setArmagent",
  "etls_setPerfInit",
  "rcSet",
  "rcSetDS",
  "etls_setDebug",
  "etls_recordCheck"
]);

const BOILERPLATE_LET_NAMES = new Set([
  "transformID",
  "trans_rc",
  "etls_stepStartTime",
  "etls_recCheckExist",
  "etls_recnt",
  "etls_sql_pushDown",
  "jobID",
  "etls_jobName",
  "etls_userID",
  "etls_startTime",
  "etls_endTime",
  "etls_recordsBefore",
  "etls_recordsAfter",
  "etls_lib",
  "etls_table",
  "IOMServer",
  "metaPort",
  "metaServer",
  "sysrc",
  "job_rc",
  "sqlrc",
  "syscc"
]);

// Anchored regex — matches ONLY the canonical DIS-generated forms. A user
// comment that adds extra text after a recognized phrase will not match.
const STRIPPABLE_NOISE_PATTERNS: ReadonlyArray<RegExp> = [
  /^\/\*\s*Runtime statistics macros\s*\*\/\s*$/,
  /^\/\*-+\s*Map the columns\s*-+\*\/\s*$/,
  /^\/\*\s*Generate the process id for job\s*\*\/\s*$/,
  /^\/\*\s*General macro variables\s*\*\/\s*$/,
  /^\/\*\s*Performance Statistics require ARM_PROC sub-system\s*\*\/\s*$/,
  /^\/\*\s*Setup to capture return codes\s*\*\/\s*$/,
  /^\/\*\s*Create metadata macro variables\s*\*\/\s*$/,
  /^\/\*\s*Setup for capturing job status\s*\*\/\s*$/,
  /^\/\*\s*initialize syserr to 0\s*\*\/\s*$/,
  /^\/\*\s*Turn off performance statistics collection\s*\*\/\s*$/,
  /^\/\*\s*Access the data for [A-Z][A-Z0-9_]*\s*\*\/\s*$/,
  /^%put\s+Process ID:\s*&SYSJOBID\s*;\s*$/,
  /^%put\s+%str\(NOTE:\s*Mapping columns\s*\.{0,3}\s*\)\s*;\s*$/
];

type DraftSegment =
  | { kind: "jobHeader"; lines: string[] }
  | { kind: "stepHeader"; lines: string[] }
  | { kind: "boilerplateMacro"; name: string; lines: string[] }
  | { kind: "boilerplateInvocation"; lines: string[] }
  | { kind: "boilerplateLet"; lines: string[] }
  | { kind: "syslast"; line: string }
  | { kind: "stepEndComment"; line: string }
  | { kind: "code"; lines: string[] };

interface Detection {
  segment: DraftSegment;
  consumed: number;
}

export function segment(input: string): Segment[] {
  const lines = input.split(/\r?\n/);
  const raw: Segment[] = [];
  let i = 0;
  while (i < lines.length) {
    const detected = detectAt(lines, i);
    if (detected) {
      raw.push(attachRange(detected.segment, i, detected.consumed));
      i += detected.consumed;
      continue;
    }
    raw.push(attachRange({ kind: "code", lines: [lines[i]] }, i, 1));
    i++;
  }
  return mergeAdjacentCode(raw);
}

function attachRange(seg: DraftSegment, i: number, consumed: number): Segment {
  return { ...seg, inputLineStart: i + 1, inputLineEnd: i + consumed } as Segment;
}

function detectAt(lines: readonly string[], i: number): Detection | null {
  return (
    detectJobHeader(lines, i) ||
    detectStepHeader(lines, i) ||
    detectBoilerplateMacro(lines, i) ||
    detectUserMacro(lines, i) ||
    detectSyslast(lines, i) ||
    detectBoilerplateLet(lines, i) ||
    detectBoilerplateGlobal(lines, i) ||
    detectStepEndComment(lines, i) ||
    detectStrippableNoise(lines, i) ||
    detectInitDataNull(lines, i) ||
    detectBoilerplateInvocation(lines, i) ||
    detectPreStepCleanup(lines, i) ||
    detectJobDataNullBlock(lines, i)
  );
}

function detectJobHeader(lines: readonly string[], i: number): Detection | null {
  if (!/^\/\*\*\*+/.test(lines[i].trim())) return null;
  if (!hasMarker(lines, i, /^\s*\*\s*Job:/i)) return null;
  const end = findCommentEnd(lines, i);
  return {
    segment: { kind: "jobHeader", lines: lines.slice(i, end + 1) },
    consumed: end - i + 1
  };
}

function detectStepHeader(lines: readonly string[], i: number): Detection | null {
  if (!/^\/\*==+/.test(lines[i].trim())) return null;
  if (!hasMarker(lines, i, /^\s*\*\s*Step:/i)) return null;
  const end = findCommentEnd(lines, i);
  return {
    segment: { kind: "stepHeader", lines: lines.slice(i, end + 1) },
    consumed: end - i + 1
  };
}

function detectBoilerplateMacro(lines: readonly string[], i: number): Detection | null {
  const m = lines[i].trim().match(/^%macro\s+([A-Za-z_]\w*)/i);
  if (!m || !BOILERPLATE_MACROS.has(m[1])) return null;
  const end = findMacroEnd(lines, i);
  if (end === -1) return null;
  return {
    segment: { kind: "boilerplateMacro", name: m[1], lines: lines.slice(i, end + 1) },
    consumed: end - i + 1
  };
}

function detectUserMacro(lines: readonly string[], i: number): Detection | null {
  const m = lines[i].trim().match(/^%macro\s+([A-Za-z_]\w*)/i);
  if (!m || BOILERPLATE_MACROS.has(m[1])) return null;
  const end = findMacroEnd(lines, i);
  if (end === -1) return null;
  return {
    segment: { kind: "code", lines: lines.slice(i, end + 1) },
    consumed: end - i + 1
  };
}

function detectSyslast(lines: readonly string[], i: number): Detection | null {
  if (!/^%let\s+SYSLAST\s*=/i.test(lines[i].trim())) return null;
  return { segment: { kind: "syslast", line: lines[i] }, consumed: 1 };
}

function detectBoilerplateLet(lines: readonly string[], i: number): Detection | null {
  const m = lines[i].trim().match(/^%let\s+([A-Za-z_]\w*)\s*=/i);
  if (!m || !BOILERPLATE_LET_NAMES.has(m[1])) return null;
  return { segment: { kind: "boilerplateLet", lines: [lines[i]] }, consumed: 1 };
}

function detectBoilerplateGlobal(lines: readonly string[], i: number): Detection | null {
  if (!/^%global\s+(etls_|applName|job_rc|trans_rc|sqlrc|_armexec)/i.test(lines[i].trim())) return null;
  return { segment: { kind: "boilerplateInvocation", lines: [lines[i]] }, consumed: 1 };
}

function detectStepEndComment(lines: readonly string[], i: number): Detection | null {
  if (!/^\/\*\*\s*Step end .*\*\*\//.test(lines[i].trim())) return null;
  return { segment: { kind: "stepEndComment", line: lines[i] }, consumed: 1 };
}

function detectStrippableNoise(lines: readonly string[], i: number): Detection | null {
  const trimmed = lines[i].trim();
  if (!STRIPPABLE_NOISE_PATTERNS.some((pattern) => pattern.test(trimmed))) return null;
  return { segment: { kind: "boilerplateInvocation", lines: [lines[i]] }, consumed: 1 };
}

function detectInitDataNull(lines: readonly string[], i: number): Detection | null {
  if (!/^data\s+_null_\s*;\s*run\s*;\s*$/i.test(lines[i].trim())) return null;
  return { segment: { kind: "boilerplateInvocation", lines: [lines[i]] }, consumed: 1 };
}

function detectBoilerplateInvocation(lines: readonly string[], i: number): Detection | null {
  const trimmed = lines[i].trim();
  const matches =
    /^%etls_(recordCheck|setPerfInit|setDebug|startPerformanceStats|setArmagent)\b/i.test(trimmed) ||
    /^%perfstrt\b/i.test(trimmed) ||
    /^%perfstop\b/i.test(trimmed) ||
    /^%perfend\b/i.test(trimmed) ||
    /^%perfinit\b/i.test(trimmed) ||
    /^%rcSet\b/i.test(trimmed) ||
    /^%rcSetDS\b/i.test(trimmed) ||
    /^option\s+DBIDIRECTEXEC\b/i.test(trimmed) ||
    /^%log4sas/i.test(trimmed);
  if (!matches) return null;
  const end = findStatementEnd(lines, i);
  return {
    segment: { kind: "boilerplateInvocation", lines: lines.slice(i, end + 1) },
    consumed: end - i + 1
  };
}

function detectPreStepCleanup(lines: readonly string[], i: number): Detection | null {
  if (!/^proc\s+datasets\s+lib\s*=\s*work\s+nolist\s+nowarn\s+memtype\s*=\s*\(\s*data\s+view\s*\)/i.test(lines[i].trim())) {
    return null;
  }
  let end = -1;
  for (let k = i; k < Math.min(i + 6, lines.length); k++) {
    if (/^\s*quit\s*;/i.test(lines[k])) {
      end = k;
      break;
    }
  }
  if (end === -1) return null;
  const body = lines.slice(i + 1, end).join("\n");
  if (!/^\s*delete\s+[A-Za-z_]\w*\s*;\s*$/m.test(body)) return null;
  return {
    segment: { kind: "boilerplateInvocation", lines: lines.slice(i, end + 1) },
    consumed: end - i + 1
  };
}

function detectJobDataNullBlock(lines: readonly string[], i: number): Detection | null {
  if (!/^data\s+_null_\s*;/i.test(lines[i].trim())) return null;
  const lookAhead = lines.slice(i, Math.min(i + 8, lines.length)).join("\n");
  const isApplName = /applName\s*=\s*"SAS Data Integration Studio"/i.test(lookAhead);
  const isPerfEnd = /if\s+"&_perfinit"\s+eq\s+"1"/i.test(lookAhead);
  if (!isApplName && !isPerfEnd) return null;
  let end = -1;
  for (let k = i; k < Math.min(i + 10, lines.length); k++) {
    if (/^\s*run\s*;/i.test(lines[k])) {
      end = k;
      break;
    }
  }
  if (end === -1) return null;
  return {
    segment: { kind: "boilerplateInvocation", lines: lines.slice(i, end + 1) },
    consumed: end - i + 1
  };
}

function hasMarker(lines: readonly string[], i: number, pattern: RegExp): boolean {
  for (let k = i + 1; k < Math.min(i + 6, lines.length); k++) {
    if (pattern.test(lines[k])) return true;
  }
  return false;
}

function findCommentEnd(lines: readonly string[], startIdx: number): number {
  for (let k = startIdx; k < lines.length; k++) {
    if (lines[k].includes("*/")) return k;
  }
  return lines.length - 1;
}

function findStatementEnd(lines: readonly string[], startIdx: number): number {
  for (let k = startIdx; k < lines.length; k++) {
    if (lines[k].includes(";")) return k;
  }
  return lines.length - 1;
}

function mergeAdjacentCode(segments: Segment[]): Segment[] {
  const merged: Segment[] = [];
  for (const seg of segments) {
    const last = merged[merged.length - 1];
    if (seg.kind === "code" && last?.kind === "code") {
      last.lines.push(...seg.lines);
      last.inputLineEnd = seg.inputLineEnd;
      continue;
    }
    merged.push(seg);
  }
  return merged;
}
