/****************************************************************************
 * Job:             load_fact_widget_summary               GENERIC.JOB00001  *
 * Description:     daily widget rollup                                      *
 *                                                                           *
 * Metadata Server: meta-host.example.com                                    *
 * Port:            8561                                                     *
 * Location:        /Apps/Analysis/widget                                    *
 *                                                                           *
 * Server:          AppServer                              GENERIC.SRV0001   *
 *                                                                           *
 * Source Tables:   widget_orders - srcdb.widget_orders    GENERIC.TBL00001  *
 *                  widget_lookup - srcdb.widget_lookup    GENERIC.TBL00002  *
 * Target Tables:   fact_widget_summary -                  GENERIC.TBL00099  *
 *                   tgtdb.fact_widget_summary                               *
 *                                                                           *
 * Generated on:    Fri, May 1 2026 1:00:00 PM                               *
 * Generated by:    user01                                                   *
 * Version:         SAS Data Integration Studio 4.905                        *
 ****************************************************************************/

/* Generate the process id for job  */
%put Process ID: &SYSJOBID;

/* General macro variables  */
%let jobID = %quote(GENERIC.JOB00001);
%let etls_jobName = %nrquote(load_fact_widget_summary);
%let etls_userID = %nrquote(user01);

%global applName;
data _null_;
applName="SAS Data Integration Studio";
call symput('applName',%nrstr(applName));
run;

/* Performance Statistics require ARM_PROC sub-system   */
%macro etls_startPerformanceStats;
   %log4sas();
   options armagent=log4sas armsubsys=(ARM_PROC);
   %perfinit(applname="&applName");
%mend;
%etls_startPerformanceStats;

/* Setup to capture return codes  */
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%let syscc = 0;
%global etls_stepStartTime;
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error);
   %if (&error gt &trans_rc) %then
      %let trans_rc = &error;
%mend rcSet;

/* Create metadata macro variables */
%let IOMServer      = %nrquote(AppServer);
%let metaPort       = %nrquote(8561);
%let metaServer     = %nrquote(meta-host.example.com);

/*==========================================================================*
 * Step:            EXT_WIDGET_ORDERS                      GENERIC.STP00001 *
 * Transform:       Extract                                                 *
 * Description:     Pull active widget orders                               *
 *                                                                          *
 * Source Table:    widget_orders - srcdb.widget_orders    GENERIC.TBL00001 *
 * Target Table:    EXT_WIDGET_ORDERS -                    GENERIC.TBL00010 *
 *                   work.EXT_WIDGET_ORDERS                                 *
 *==========================================================================*
 * Quick Note:                                                              *
 * 01-May-2026                                                              *
 * Pull only active orders from the last 30 days.                           *
 *==========================================================================*/

%let transformID = %quote(GENERIC.STP00001);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.);

/* Access the data for SRCDB  */
LIBNAME srcdb TERADATA SERVER="src.example.com" SCHEMA=PUBLIC;
%rcSet(&syslibrc);

%let etls_recnt = 0;
%macro etls_recordCheck;
   %let etls_recCheckExist = %eval(%sysfunc(exist(srcdb.widget_orders, DATA)));
   %if (&etls_recCheckExist) %then
   %do;
      proc sql noprint;
         select count(*) into :etls_recnt from srcdb.widget_orders;
      quit;
   %end;
%mend etls_recordCheck;
%etls_recordCheck;

%let SYSLAST = %nrquote(srcdb.widget_orders);

/* Runtime statistics macros  */
%etls_setPerfInit;
%perfstrt(txnname=%BQUOTE(_DISARM|&transformID|&syshostname|Extract), metrNam6=_DISROWCNT, metrDef6=Count32);

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/
proc datasets lib = work nolist nowarn memtype = (data view);
   delete EXT_WIDGET_ORDERS;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create table work.EXT_WIDGET_ORDERS as
      select
         order_id,
         widget_id,
         customer_id,
         /* keep only active orders */
         order_status,
         order_date
   from &SYSLAST
      where order_status = 'ACTIVE'
        and order_date > today() - 30
   ;
quit;

%let SYSLAST = work.EXT_WIDGET_ORDERS;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc);

%perfstop(metrVal6=%sysfunc(max(&etls_recnt,-1)));
%let etls_recnt=-1;



/** Step end EXT_WIDGET_ORDERS **/

/*==========================================================================*
 * Step:            JOIN_WITH_LOOKUP                       GENERIC.STP00002 *
 * Transform:       Join                                                    *
 * Description:                                                             *
 *                                                                          *
 * Source Tables:   EXT_WIDGET_ORDERS -                    GENERIC.TBL00010 *
 *                   work.EXT_WIDGET_ORDERS                                 *
 *                  widget_lookup - srcdb.widget_lookup    GENERIC.TBL00002 *
 * Target Table:    JOINED_WIDGETS -                       GENERIC.TBL00020 *
 *                   work.JOINED_WIDGETS                                    *
 *==========================================================================*
 * Warnings:                                                                *
 * Column widget_name truncated to 50 chars.                                *
 *==========================================================================*/

%let transformID = %quote(GENERIC.STP00002);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.);

%let etls_recnt = 0;
%macro etls_recordCheck;
   %let etls_recCheckExist = %eval(%sysfunc(exist(work.EXT_WIDGET_ORDERS, DATA)));
%mend etls_recordCheck;
%etls_recordCheck;

%let SYSLAST = %nrquote(work.EXT_WIDGET_ORDERS);

/* Runtime statistics macros  */
%etls_setPerfInit;
%perfstrt(txnname=%BQUOTE(_DISARM|&transformID|&syshostname|SQLJoin), metrNam6=_DISROWCNT, metrDef6=Count32);

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete JOINED_WIDGETS;
quit;

proc sql;
   create table work.JOINED_WIDGETS as
   select
      o.order_id,
      o.widget_id,
      o.customer_id,
      l.widget_name length = 50 label = 'widget_name',
      l.widget_category,
      o.order_date
   from
      work.EXT_WIDGET_ORDERS as o
   left join
      srcdb.widget_lookup as l
      on o.widget_id = l.widget_id
   ;
quit;

%let SYSLAST = work.JOINED_WIDGETS;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc);

%perfstop(metrVal6=%sysfunc(max(&etls_recnt,-1)));
%let etls_recnt=-1;



/** Step end JOIN_WITH_LOOKUP **/

/*==========================================================================*
 * Step:            LOAD_TARGET                            GENERIC.STP00003 *
 * Transform:       Loader                                                  *
 * Description:     Append to fact_widget_summary                           *
 *==========================================================================*/

%let transformID = %quote(GENERIC.STP00003);
%let trans_rc = 0;

%macro etls_loader;
   %let etls_lastTable = &SYSLAST;
   proc append base = tgtdb.fact_widget_summary
               data = &etls_lastTable force;
   run;
   %rcSet(&syserr);
%mend etls_loader;
%etls_loader;

%perfstop(metrVal6=%sysfunc(max(&etls_recnt,-1)));
%let etls_recnt=-1;



/** Step end LOAD_TARGET **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/* Turn off performance statistics collection  */
data _null_;
   if "&_perfinit" eq "1" then
      call execute('%perfend;');
run;
